name: 定时拉取

on:
   push:
     branches:
     - master   
   schedule:
   - cron: "*/30 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
          
    - name: 拉取订阅
      run: |

         curl ${{ secrets.SPEED }} > speed.png
         
         curl ${{ secrets.LINK_URL }} > link_url.txt
         
         curl ${{ secrets.V2RAY }} > v2ray.txt
         
         curl ${{ secrets.CLASH }} > clash.yml
      
         sed -i "1c 节点更新时间：`date +'%Y-%m-%d %H:%M:%S'`" README.md
         
         git pull
         git config --local user.email "classccai@gmail.com"
         git config --local user.name "classcwz"
         git add .
         git commit -am "更新订阅链接"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         branch: master
